In [1]:
pip install tensorflow

  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4848 sha256=d1f47a749e25085b7f5a575abe9fea57e85280aea7a28c19058ca57ef5aaf9f3
  Stored in directory: c:\users\student\appdata\local\pip\cache\wheels\b6\0d\90\0d1bbd99855f99cb2f6c2e5ff96f8023fad8ec367695f7d72d
Successfully built termcolor
Note: you may need to restart the kernel to use updated packages.


### import tensorflow

In [5]:
import tensorflow as tf
tf.__version__

'2.9.1'

In [6]:
import numpy as np
import pandas as pd
import tensorflow as tf

data = pd.read_csv("C:/Users/Student/Downloads/Galgotias-University-main/Galgotias-University-main/Churn_Modelling.csv")

In [7]:
x=data.iloc[:,3:7].values
y=data.iloc[:,-1].values

In [8]:
print(x)

[[619 'France' 'Female' 42]
 [608 'Spain' 'Female' 41]
 [502 'France' 'Female' 42]
 ...
 [709 'France' 'Female' 36]
 [772 'Germany' 'Male' 42]
 [792 'France' 'Female' 28]]


In [9]:
print(y)

[1 0 1 ... 1 1 0]


In [10]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
x[:,2]= le.fit_transform(x[:,2])

In [11]:
print(x)

[[619 'France' 0 42]
 [608 'Spain' 0 41]
 [502 'France' 0 42]
 ...
 [709 'France' 0 36]
 [772 'Germany' 1 42]
 [792 'France' 0 28]]


In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [13]:
print(x)

[[1.0 0.0 0.0 619 0 42]
 [0.0 0.0 1.0 608 0 41]
 [1.0 0.0 0.0 502 0 42]
 ...
 [1.0 0.0 0.0 709 0 36]
 [0.0 1.0 0.0 772 1 42]
 [1.0 0.0 0.0 792 0 28]]


In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [16]:
ann = tf.keras.models.Sequential()

In [17]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [18]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [19]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [20]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [21]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)


Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5046 - accuracy: 0.7849
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4489 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4427 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4405 - accuracy: 0.7961
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4388 - accuracy: 0.7962
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4378 - accuracy: 0.7966
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4369 - accuracy: 0.8014
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4362 - accuracy: 0.8021
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4355 - accuracy: 0.8065
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4351 - accura

250/250 [==============================] - 0s 1ms/step - loss: 0.4190 - accuracy: 0.8165
Epoch 82/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4189 - accuracy: 0.8171
Epoch 83/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4191 - accuracy: 0.8167
Epoch 84/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4185 - accuracy: 0.8185
Epoch 85/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4186 - accuracy: 0.8171
Epoch 86/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4186 - accuracy: 0.8164
Epoch 87/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4186 - accuracy: 0.8174
Epoch 88/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4183 - accuracy: 0.8171
Epoch 89/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4188 - accuracy: 0.8179
Epoch 90/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4188 - accuracy: 

In [22]:

y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 1s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1521   74]
 [ 271  134]]


0.8275